### ISSUE TITLE
More current info on failed searches

### ISSUE THREAD

**Issue by iMazed** [dannyvankooten/wp-knowledge-base#30]
In the admin dashboard is a 'Failed Searches' section. For now it only shows all the failed searches from the past 30 days. Please add more recent dates too, like 'today', 'yesterday', etc. Helps keeping track of what needs to be done a lot more.

![2015-08-31 11_23_28- search statistics mailchimp for wordpress wordpress](https://cloud.githubusercontent.com/assets/3907432/9575798/b9963c88-4fd2-11e5-8459-471de548bc1f.png)

**Comment by dannyvankooten** [comment]
This is handled using the SearchWP plugin. 

Please tweet [@JCristopher](https://twitter.com/jchristopher) or [@SearchWP](https://twitter.com/searchwp) about this, he's very responsive. :smiley:
