### ISSUE TITLE
Rating: Only allow rating once per article per visitor

### ISSUE THREAD

**Issue by dannyvankooten** [dannyvankooten/wp-knowledge-base#6]
Based on IP or session?

**Comment by dannyvankooten** [comment]
We're not so sure about this one yet, but some kind of rate limiting to prevent spam / skewed results would be good.

**Comment by hchouhan** [comment]
In my plugin https://wordpress.org/plugins/i-recommend-this/, I use cookie based as well as option to save user IP to prevent spamming. I had made the plugin for a gallery site (http://flattrendz.com). IP thing does make the whole thing bit slower.
